START TRANSACTION;

UPDATE cv SET identifier = 'https://creativecommons.org/publicdomain/mark/1.0/', description_sv = 'Det här verket har identifierats som fritt från kända upphovsrättsliga restriktioner, inklusive alla relaterade närstående rättigheter.', description_en = 'This work has been identified as being free of known restrictions under copyright law, including all related and neighboring rights.', text_sv = 'Public domain-märke 1.0', text_en = 'Public Domain Mark 1.0'  WHERE slug = 'public-domain';
UPDATE cv SET identifier = 'https://creativecommons.org/publicdomain/zero/1.0/', description_sv = 'Personen som associerat ett verk med detta dokument har dedikerat verket till public domain genom att avsäga sig sina rättigheter till verket i hela världen enligt upphovsrättslagstiftningen, inklusive alla relaterade och närstående rättigheter, så lågt lagen tillåter. ', description_en = 'The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law. ', text_sv = 'Creative Commons  Public domain-dedikation  (CC0 1.0)', text_en = 'Creative Commons  Public Domain Dedication (CC0 1.0)'  WHERE slug = 'cc0';
UPDATE cv SET identifier = 'https://creativecommons.org/licenses/by/4.0/', description_sv = 'Du har tillstånd att: Dela — kopiera och vidaredistribuera materialet oavsett medium eller format. Bearbeta — remixa, transformera, och bygg vidare på materialet för alla ändamål, även kommersiellt. ', description_en = 'You are free to: Share — copy and redistribute the material in any medium or format. Adapt — remix, transform, and build upon the material for any purpose, even commercially. ', text_sv = 'Creative Commons  Erkännande 4.0 Internationell (CC BY 4.0)', text_en = 'Creative Commons  Attribution 4.0 International (CC BY 4.0)'  WHERE slug = 'cc-by-40';
UPDATE cv SET identifier = 'https://creativecommons.org/licenses/by-nc/4.0/', description_sv = 'Du har tillstånd att: Dela — kopiera och vidaredistribuera materialet oavsett medium eller format. Bearbeta — remixa, transformera, och bygg vidare på materialet .', description_en = 'You are free to: Share — copy and redistribute the material in any medium or format. Adapt — remix, transform, and build upon the material.', text_sv = 'Creative Commons  Erkännande-Icke Kommersiell 4.0 Internationell (CC BY-NC 4.0)', text_en = 'Creative Commons Attribution-NonCommercial 4.0 International (CC BY-NC 4.0)'  WHERE slug = 'cc-by-nc-40';
UPDATE cv SET identifier = 'https://creativecommons.org/licenses/by-nc-nd/4.0/', description_sv = 'Du har tillstånd att: Dela — kopiera och vidaredistribuera materialet oavsett medium eller format.', description_en = 'You are free to: Share — copy and redistribute the material in any medium or format.', text_sv = 'Creative Commons  Erkännande-Icke kommersiell-Inga Bearbetningar 4.0 Internationell (CC BY-NC-ND 4.0)', text_en = 'Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)'  WHERE slug = 'cc-by-nc-nd-40';
UPDATE cv SET identifier = 'https://creativecommons.org/licenses/by-nc-sa/4.0/', description_sv = 'Du har tillstånd att: Dela — kopiera och vidaredistribuera materialet oavsett medium eller format. Bearbeta — remixa, transformera, och bygg vidare på materialet.', description_en = 'You are free to: Share — copy and redistribute the material in any medium or format. Adapt — remix, transform, and build upon the material.', text_sv = 'Creative Commons  Erkännande-Icke Kommersiell-Dela Lika 4.0 Internationell (CC BY-NC-SA 4.0)', text_en = 'Creative Commons  Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)'  WHERE slug = 'cc-by-nc-sa-40';
UPDATE cv SET identifier = 'https://creativecommons.org/licenses/by-nd/4.0/', description_sv = 'Du har tillstånd att: Dela — kopiera och vidaredistribuera materialet oavsett medium eller format för alla ändamål, även kommersiellt.', description_en = 'You are free to: Share — copy and redistribute the material in any medium or format for any purpose, even commercially. ', text_sv = 'Creative Commons  Erkännande-Inga Bearbetningar 4.0 Internationell (CC BY-ND 4.0)', text_en = 'Creative Commons  Attribution-NoDerivatives 4.0 International (CC BY-ND 4.0)'  WHERE slug = 'cc-by-nd-40';
UPDATE cv SET identifier = 'https://creativecommons.org/licenses/by-sa/4.0/', description_sv = 'Du har tillstånd att: Dela — kopiera och vidaredistribuera materialet oavsett medium eller format. Bearbeta — remixa, transformera, och bygg vidare på materialet för alla ändamål, även kommersiellt.', description_en = 'You are free to: Share — copy and redistribute the material in any medium or format. Adapt — remix, transform, and build upon the material for any purpose, even commercially.', text_sv = 'Creative Commons  Erkännande-Dela Lika 4.0 Internationell (CC BY-SA 4.0)', text_en = 'Creative Commons  Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)'  WHERE slug = 'cc-by-sa-40';
UPDATE cv SET identifier = 'https://opendatacommons.org/licenses/odbl/1-0/', description_sv = '', description_en = '', text_sv = 'Open Data Commons Open Database License (ODbL 1.0)', text_en = 'Open Data Commons Open Database License (ODbL 1.0)'  WHERE slug = 'odbl-10';
UPDATE cv SET identifier = 'https://opendatacommons.org/licenses/pddl/1-0/', description_sv = '', description_en = '', text_sv = 'Open Data Commons Public Domain Dedication and License (PDDL 1.0)', text_en = 'Open Data Commons Public Domain Dedication and License (PDDL 1.0)'  WHERE slug = 'pddl-10';
UPDATE cv SET identifier = 'https://opendatacommons.org/licenses/by/1-0/', description_sv = '', description_en = '', text_sv = 'Open Data Commons Attribution License (ODC-By 1.0)', text_en = 'Open Data Commons Attribution License (ODC-By 1.0)'  WHERE slug = 'odc-by-10';

COMMIT;
